### ISSUE TITLE
Using of interval avoidance met some error

### ISSUE THREAD

**Issue by HBH-THU** [douthwja01/OpenMAS#6]
Hello Douthwaite, sorry to bother you, i met some error when I use the code "agentIndex{index} = agent_interval(); ",  it is shown below:

Error in modpi2>modpi2fast (line 74)
  x = ( x + (-k)*INTLAB_STDFCTS_PI.PI2_1 ) + ... % exact for abs(x)<=2^27
Error in modpi2 (line 43)
  [ yinf , ysup , s , index ] = modpi2fast(x);
Error in intval/sin (line 47)
  [ xinfinf , xinfsup , Sinf ] = modpi2(x.inf(:));
Error in agent.GetRadiusFromAngularWidth (line 504)
            r = (sin(alpha/2)/(1-sin(alpha/2)))*d;
Error in agent_interval/SensorModel (line 172)
            radiusBox = this.GetRadiusFromAngularWidth(rangeBox,alphaBox);
Error in agent/GetAgentUpdate (line 157)
                sensedobject = this.SensorModel(ENV.dt,observedobjects(entry));
Error in agent_interval/main (line 65)
            [this,obstacleSet,agentSet] = this.GetAgentUpdate(ENV,varargin{1});
Error in OMAS_process>UpdateObjects (line 580)
            referenceObject = referenceObject.main(ENV,observationPacket);                      % Hand the current sim TIME object and complete observation packet
Error in OMAS_process>ProcessGlobalTimeSeries (line 138)
            [objectIndex{ID1},objectEVENTS] = UpdateObjects(META,objectIndex,objectIndex{ID1}); % Update objectIndex snapshot with new META data
Error in OMAS_process (line 25)
[META,objectIndex,DATA,EVENTS] = ProcessGlobalTimeSeries(META,objectIndex,DATA,EVENTS);
Error in OMAS_initialise (line 130)
[DATA,META,EVENTS,objectIndex] = OMAS_process(META,objectIndex);
Error in example_setup (line 160)
[DATA,META] = OMAS_initialise('objects',objectIndex,...

would you mind doing me a favor to help me solve this problem, I will be really appreciated for any help from you, thanks

**Comment by mengchaoheng** [comment]
@HBH-THU Could you run the example?

**Comment by douthwja01** [comment]
hi there, so, when i've tried to reproduce this, it seems to be an issue with the Intlab library.. I suspect it may now only work with 2020 and earlier versions. Unfortunately this is outside of my control!
