### ISSUE TITLE
Unrecognized method, property, or field 'SetRadius' for class 'agent_example'.

### ISSUE THREAD

**Issue by mengchaoheng** [douthwja01/OpenMAS#7]
```
>> example_setup
[SETUP]	Initialising example script.
[SETUP]	Assigning agent definitions:
objectcount: 1	name: alpha001	type: agent_example
objectcount: 2	name: beta001	type: agent_example
Unrecognized method, property, or field 'SetRadius' for class 'agent_example'.

Error in agent_example (line 50)
            obj = obj.SetRadius(0.5);

Error in example_setup (line 60)
    agentIndex{index} = agent_example('radius',sim_agentRadius);
t
```

**Comment by mengchaoheng** [comment]
when I delete the `agent_example` file of examples folder, it run ! But have a new situation:
```
>> example_setup
[SETUP]	Initialising example script.
[SETUP]	Assigning agent definitions:
objectcount: 1	name: alpha001	type: agent_example
objectcount: 2	name: beta001	type: agent_example
objectcount: 3	name: gamma001	type: agent_example
objectcount: 4	name: delta001	type: agent_example
objectcount: 5	name: epsilon001	type: agent_example
[SCENARIO]	Getting typical concentric agent scenario.
[SCENARIO]	Assigning agent global parameters...
[SCENARIO]	Assigning waypoint definitions:
objectcount: 6	name: WP-alpha001	type: waypoint
objectcount: 7	name: WP-beta001	type: waypoint
objectcount: 8	name: WP-gamma001	type: waypoint
objectcount: 9	name: WP-delta001	type: waypoint
objectcount: 10	name: WP-epsilon001	type: waypoint
[SETUP]	Confirming input variables.
[SETUP] --> Input parameters defined.

[SETUP]	INITIALISING SIMULATION...

[SETUP]	OMAS CONFIGURATION:
[SETUP]	Objects parameterized.
[SETUP]	OUTPUT CONFIGURATION:
[SETUP]	Session output directory created: 
[SETUP]	"2023-06-10@01-38-03-session-data" 
[SETUP]	Output path: 
[SETUP]	"%USERPROFILE%/desktop/openmas-data/2023-06-10@01-38-03-session-data/"
[SETUP]	CONFIGURATION SUMMARY:
[SETUP]	Objects: 10	Agents: 5	Obstacles: 0	Waypoints: 5
[SETUP]	Max Steps: 151	 Max Duration: 15.00s	 dt: 0.100s	
[SETUP]	Moving to simulation...
[META]
[META]	LAUNCHING SIMULATION...
[META]
[META]	Step: 1	Time: 0.00s
[META]	Step: 2	Time: 0.10s
[META]	Step: 3	Time: 0.20s
[META]	Step: 4	Time: 0.30s
[META]	Step: 5	Time: 0.40s
[META]	Step: 6	Time: 0.50s
[META]	Step: 7	Time: 0.60s
[META]	Step: 8	Time: 0.70s
[META]	Step: 9	Time: 0.80s
[META]	Step: 10	Time: 0.90s
[META]	Step: 11	Time: 1.00s
[META]	Step: 12	Time: 1.10s
[META]	Step: 13	Time: 1.20s
[META]	Step: 14	Time: 1.30s
[META]	Step: 15	Time: 1.40s
[META]	Step: 16	Time: 1.50s
[META]	Step: 17	Time: 1.60s
[META]	Step: 18	Time: 1.70s
[META]	Step: 19	Time: 1.80s
[META]	Step: 20	Time: 1.90s
[META]	Step: 21	Time: 2.00s
[META]	Step: 22	Time: 2.10s
[META]	Step: 23	Time: 2.20s
[META]	Step: 24	Time: 2.30s
[META]	Step: 25	Time: 2.40s
[META]	Step: 26	Time: 2.50s
[META]	Step: 27	Time: 2.60s
[META]	Step: 28	Time: 2.70s
[META]	Step: 29	Time: 2.80s
[META]	Step: 30	Time: 2.90s
[META]	Step: 31	Time: 3.00s
[META]	Step: 32	Time: 3.10s
[META]	Step: 33	Time: 3.20s
[META]	Step: 34	Time: 3.30s
[META]	Step: 35	Time: 3.40s
[META]	Step: 36	Time: 3.50s
[META]	Step: 37	Time: 3.60s
[META]	Step: 38	Time: 3.70s
[META]	Step: 39	Time: 3.80s
[META]	Step: 40	Time: 3.90s
[META]	Step: 41	Time: 4.00s
[META]	Step: 42	Time: 4.10s
[META]	Step: 43	Time: 4.20s
[META]	Step: 44	Time: 4.30s
[META]	Step: 45	Time: 4.40s
[META]	Step: 46	Time: 4.50s
[META]	Step: 47	Time: 4.60s
[META]	Step: 48	Time: 4.70s
[META]	Step: 49	Time: 4.80s
[META]	Step: 50	Time: 4.90s
[META]	Step: 51	Time: 5.00s
[META]	Step: 52	Time: 5.10s
[META]	Step: 53	Time: 5.20s
[META]	Step: 54	Time: 5.30s
[META]	Step: 55	Time: 5.40s
[META]	Step: 56	Time: 5.50s
[META]	Step: 57	Time: 5.60s
[META]	Step: 58	Time: 5.70s
[META]	Step: 59	Time: 5.80s
[META]	Step: 60	Time: 5.90s
[META]	Step: 61	Time: 6.00s
[META]	Step: 62	Time: 6.10s
[META]	Step: 63	Time: 6.20s
[META]	Step: 64	Time: 6.30s
[META]	Step: 65	Time: 6.40s
[META]	Step: 66	Time: 6.50s
[META]	Step: 67	Time: 6.60s
[META]	Step: 68	Time: 6.70s
[META]	Step: 69	Time: 6.80s
[META]	Step: 70	Time: 6.90s
[META]	Step: 71	Time: 7.00s
[META]	Step: 72	Time: 7.10s
[META]	Step: 73	Time: 7.20s
[META]	Step: 74	Time: 7.30s
[META]	Step: 75	Time: 7.40s
[META]	Step: 76	Time: 7.50s
[META]	Step: 77	Time: 7.60s
[META]	Step: 78	Time: 7.70s
[META]	Step: 79	Time: 7.80s
[META]	Step: 80	Time: 7.90s
[META]	Step: 81	Time: 8.00s
[META]	Step: 82	Time: 8.10s
[META]	Step: 83	Time: 8.20s
[META]	Step: 84	Time: 8.30s
[META]	Step: 85	Time: 8.40s
[META]	Step: 86	Time: 8.50s
[META]	Step: 87	Time: 8.60s
[META]	Step: 88	Time: 8.70s
[META]	Step: 89	Time: 8.80s
[META]	Step: 90	Time: 8.90s
[META]	Step: 91	Time: 9.00s
[META]	Step: 92	Time: 9.10s
[META]	Step: 93	Time: 9.20s
[META]	Step: 94	Time: 9.30s
[META]	Step: 95	Time: 9.40s
[META]	Step: 96	Time: 9.50s
[META]	Step: 97	Time: 9.60s
[META]	Step: 98	Time: 9.70s
[META]	Step: 99	Time: 9.80s
[META]	Step: 100	Time: 9.90s
[META]	Step: 101	Time: 10.00s
[META]	Step: 102	Time: 10.10s
[META]	Step: 103	Time: 10.20s
[META]	Step: 104	Time: 10.30s
[META]	Step: 105	Time: 10.40s
[META]	Step: 106	Time: 10.50s
[META]	Step: 107	Time: 10.60s
[META]	Step: 108	Time: 10.70s
[META]	Step: 109	Time: 10.80s
[META]	Step: 110	Time: 10.90s
[META]	Step: 111	Time: 11.00s
[META]	Step: 112	Time: 11.10s
[META]	Step: 113	Time: 11.20s
[META]	Step: 114	Time: 11.30s
[META]	Step: 115	Time: 11.40s
[META]	Step: 116	Time: 11.50s
[META]	Step: 117	Time: 11.60s
[META]	Step: 118	Time: 11.70s
[META]	Step: 119	Time: 11.80s
[META]	Step: 120	Time: 11.90s
[META]	Step: 121	Time: 12.00s
[META]	Step: 122	Time: 12.10s
[META]	Step: 123	Time: 12.20s
[META]	Step: 124	Time: 12.30s
[META]	Step: 125	Time: 12.40s
[META]	Step: 126	Time: 12.50s
[META]	Step: 127	Time: 12.60s
[META]	Step: 128	Time: 12.70s
[META]	Step: 129	Time: 12.80s
[META]	Step: 130	Time: 12.90s
[META]	Step: 131	Time: 13.00s
[META]	Step: 132	Time: 13.10s
[META]	Step: 133	Time: 13.20s
[META]	Step: 134	Time: 13.30s
[META]	Step: 135	Time: 13.40s
[META]	Step: 136	Time: 13.50s
[META]	Step: 137	Time: 13.60s
[META]	Step: 138	Time: 13.70s
[META]	Step: 139	Time: 13.80s
[META]	Step: 140	Time: 13.90s
[META]	Step: 141	Time: 14.00s
[META]	Step: 142	Time: 14.10s
[META]	Step: 143	Time: 14.20s
[META]	Step: 144	Time: 14.30s
[META]	Step: 145	Time: 14.40s
[META]	Step: 146	Time: 14.50s
[META]	Step: 147	Time: 14.60s
[META]	Step: 148	Time: 14.70s
[META]	Step: 149	Time: 14.80s
[META]	Step: 150	Time: 14.90s
[META]	Step: 151	Time: 15.00s
[META]
[META]	...SIMULATION COMPLETE
[META]
[OUTPUT]	Dumping initial simulation variables to output directory
[OUTPUT]
[OUTPUT]	Closing simulation.
[OUTPUT]	Operation lasted 7.48s.
[OUTPUT]	Moving to post-simulation analysis...
[OUTPUT]
[OUTPUT]	OMAS ANALYSIS TOOL...
[OUTPUT]
[OUTPUT]	Moving to event data parser...
[OUTPUT]	Parsing simulation EVENT data...
[OUTPUT]
[OUTPUT]	EVENT statistics collected.
[OUTPUT]
[OUTPUT]	Moving to agent data parser...
[OUTPUT]	Parsing AGENT data...

[OUTPUT]	OMAS FIGURE GENERATOR (OMAS_figureGenerator.m).
[OUTPUT]
[OUTPUT]	Generating the event overview figure.
[OUTPUT}	Generating top-down 2D(plan) figure.
Warning: [OMAS-error] A problem occurred generating the output figures. 
> In OMAS_analysis (line 99)
In OMAS_initialise (line 137)
In example_setup (line 157) 
Warning: Undefined function 'OMAS_getTrajectoryData_mex' for input arguments of type 'uint16'. 
> In OMAS_analysis (line 100)
In OMAS_initialise (line 137)
In example_setup (line 157) 

Warning: [ERROR] A problem occurred interpreting the output data 
> In OMAS_initialise (line 139)
In example_setup (line 157) 
Unrecognized function or variable 'OMAS_getTrajectoryData_mex'.

Error in GetFigure_plan (line 21)
    [finalStates] = OMAS_getTrajectoryData_mex(...

Error in OMAS_figureGenerator (line 79)
        [figureNumber,~] = GetFigure_plan(SIM,objectIndex,DATA,figureNumber);

Error in OMAS_analysis (line 97)
        [plotnum] = OMAS_figureGenerator(META,OBJECTS,DATA,plotnum,figureList(figNum)); % Jump to the figure index

Error in OMAS_initialise (line 137)
    [DATA] = OMAS_analysis(META,objectIndex,EVENTS,DATA);                  % Jump to external analysis program

Error in example_setup (line 157)
[DATA,META] = OMAS_initialise('objects',objectIndex,...
 
>> 
```
I use m1 macbook, maybe need a `mexmaci64` instead `.mexw64`

**Comment by douthwja01** [comment]
> ```
> >> example_setup
> [SETUP]	Initialising example script.
> [SETUP]	Assigning agent definitions:
> objectcount: 1	name: alpha001	type: agent_example
> objectcount: 2	name: beta001	type: agent_example
> Unrecognized method, property, or field 'SetRadius' for class 'agent_example'.
> 
> Error in agent_example (line 50)
>             obj = obj.SetRadius(0.5);
> 
> Error in example_setup (line 60)
>     agentIndex{index} = agent_example('radius',sim_agentRadius);
> t
> ```

Thank you for identifying this, it is a legacy reference, now replaced by "obj.radius = 0.5". I have pushed the change

**Comment by douthwja01** [comment]
> when I delete the `agent_example` file of examples folder, it run ! But have a new situation:
> 
> ```
> >> example_setup
> [SETUP]	Initialising example script.
> [SETUP]	Assigning agent definitions:
> objectcount: 1	name: alpha001	type: agent_example
> objectcount: 2	name: beta001	type: agent_example
> objectcount: 3	name: gamma001	type: agent_example
> objectcount: 4	name: delta001	type: agent_example
> objectcount: 5	name: epsilon001	type: agent_example
> [SCENARIO]	Getting typical concentric agent scenario.
> [SCENARIO]	Assigning agent global parameters...
> [SCENARIO]	Assigning waypoint definitions:
> objectcount: 6	name: WP-alpha001	type: waypoint
> objectcount: 7	name: WP-beta001	type: waypoint
> objectcount: 8	name: WP-gamma001	type: waypoint
> objectcount: 9	name: WP-delta001	type: waypoint
> objectcount: 10	name: WP-epsilon001	type: waypoint
> [SETUP]	Confirming input variables.
> [SETUP] --> Input parameters defined.
> 
> [SETUP]	INITIALISING SIMULATION...
> 
> [SETUP]	OMAS CONFIGURATION:
> [SETUP]	Objects parameterized.
> [SETUP]	OUTPUT CONFIGURATION:
> [SETUP]	Session output directory created: 
> [SETUP]	"2023-06-10@01-38-03-session-data" 
> [SETUP]	Output path: 
> [SETUP]	"%USERPROFILE%/desktop/openmas-data/2023-06-10@01-38-03-session-data/"
> [SETUP]	CONFIGURATION SUMMARY:
> [SETUP]	Objects: 10	Agents: 5	Obstacles: 0	Waypoints: 5
> [SETUP]	Max Steps: 151	 Max Duration: 15.00s	 dt: 0.100s	
> [SETUP]	Moving to simulation...
> [META]
> [META]	LAUNCHING SIMULATION...
> [META]
> [META]	Step: 1	Time: 0.00s
> [META]	Step: 2	Time: 0.10s
> [META]	Step: 3	Time: 0.20s
> [META]	Step: 4	Time: 0.30s
> [META]	Step: 5	Time: 0.40s
> [META]	Step: 6	Time: 0.50s
> [META]	Step: 7	Time: 0.60s
> [META]	Step: 8	Time: 0.70s
> [META]	Step: 9	Time: 0.80s
> [META]	Step: 10	Time: 0.90s
> [META]	Step: 11	Time: 1.00s
> [META]	Step: 12	Time: 1.10s
> [META]	Step: 13	Time: 1.20s
> [META]	Step: 14	Time: 1.30s
> [META]	Step: 15	Time: 1.40s
> [META]	Step: 16	Time: 1.50s
> [META]	Step: 17	Time: 1.60s
> [META]	Step: 18	Time: 1.70s
> [META]	Step: 19	Time: 1.80s
> [META]	Step: 20	Time: 1.90s
> [META]	Step: 21	Time: 2.00s
> [META]	Step: 22	Time: 2.10s
> [META]	Step: 23	Time: 2.20s
> [META]	Step: 24	Time: 2.30s
> [META]	Step: 25	Time: 2.40s
> [META]	Step: 26	Time: 2.50s
> [META]	Step: 27	Time: 2.60s
> [META]	Step: 28	Time: 2.70s
> [META]	Step: 29	Time: 2.80s
> [META]	Step: 30	Time: 2.90s
> [META]	Step: 31	Time: 3.00s
> [META]	Step: 32	Time: 3.10s
> [META]	Step: 33	Time: 3.20s
> [META]	Step: 34	Time: 3.30s
> [META]	Step: 35	Time: 3.40s
> [META]	Step: 36	Time: 3.50s
> [META]	Step: 37	Time: 3.60s
> [META]	Step: 38	Time: 3.70s
> [META]	Step: 39	Time: 3.80s
> [META]	Step: 40	Time: 3.90s
> [META]	Step: 41	Time: 4.00s
> [META]	Step: 42	Time: 4.10s
> [META]	Step: 43	Time: 4.20s
> [META]	Step: 44	Time: 4.30s
> [META]	Step: 45	Time: 4.40s
> [META]	Step: 46	Time: 4.50s
> [META]	Step: 47	Time: 4.60s
> [META]	Step: 48	Time: 4.70s
> [META]	Step: 49	Time: 4.80s
> [META]	Step: 50	Time: 4.90s
> [META]	Step: 51	Time: 5.00s
> [META]	Step: 52	Time: 5.10s
> [META]	Step: 53	Time: 5.20s
> [META]	Step: 54	Time: 5.30s
> [META]	Step: 55	Time: 5.40s
> [META]	Step: 56	Time: 5.50s
> [META]	Step: 57	Time: 5.60s
> [META]	Step: 58	Time: 5.70s
> [META]	Step: 59	Time: 5.80s
> [META]	Step: 60	Time: 5.90s
> [META]	Step: 61	Time: 6.00s
> [META]	Step: 62	Time: 6.10s
> [META]	Step: 63	Time: 6.20s
> [META]	Step: 64	Time: 6.30s
> [META]	Step: 65	Time: 6.40s
> [META]	Step: 66	Time: 6.50s
> [META]	Step: 67	Time: 6.60s
> [META]	Step: 68	Time: 6.70s
> [META]	Step: 69	Time: 6.80s
> [META]	Step: 70	Time: 6.90s
> [META]	Step: 71	Time: 7.00s
> [META]	Step: 72	Time: 7.10s
> [META]	Step: 73	Time: 7.20s
> [META]	Step: 74	Time: 7.30s
> [META]	Step: 75	Time: 7.40s
> [META]	Step: 76	Time: 7.50s
> [META]	Step: 77	Time: 7.60s
> [META]	Step: 78	Time: 7.70s
> [META]	Step: 79	Time: 7.80s
> [META]	Step: 80	Time: 7.90s
> [META]	Step: 81	Time: 8.00s
> [META]	Step: 82	Time: 8.10s
> [META]	Step: 83	Time: 8.20s
> [META]	Step: 84	Time: 8.30s
> [META]	Step: 85	Time: 8.40s
> [META]	Step: 86	Time: 8.50s
> [META]	Step: 87	Time: 8.60s
> [META]	Step: 88	Time: 8.70s
> [META]	Step: 89	Time: 8.80s
> [META]	Step: 90	Time: 8.90s
> [META]	Step: 91	Time: 9.00s
> [META]	Step: 92	Time: 9.10s
> [META]	Step: 93	Time: 9.20s
> [META]	Step: 94	Time: 9.30s
> [META]	Step: 95	Time: 9.40s
> [META]	Step: 96	Time: 9.50s
> [META]	Step: 97	Time: 9.60s
> [META]	Step: 98	Time: 9.70s
> [META]	Step: 99	Time: 9.80s
> [META]	Step: 100	Time: 9.90s
> [META]	Step: 101	Time: 10.00s
> [META]	Step: 102	Time: 10.10s
> [META]	Step: 103	Time: 10.20s
> [META]	Step: 104	Time: 10.30s
> [META]	Step: 105	Time: 10.40s
> [META]	Step: 106	Time: 10.50s
> [META]	Step: 107	Time: 10.60s
> [META]	Step: 108	Time: 10.70s
> [META]	Step: 109	Time: 10.80s
> [META]	Step: 110	Time: 10.90s
> [META]	Step: 111	Time: 11.00s
> [META]	Step: 112	Time: 11.10s
> [META]	Step: 113	Time: 11.20s
> [META]	Step: 114	Time: 11.30s
> [META]	Step: 115	Time: 11.40s
> [META]	Step: 116	Time: 11.50s
> [META]	Step: 117	Time: 11.60s
> [META]	Step: 118	Time: 11.70s
> [META]	Step: 119	Time: 11.80s
> [META]	Step: 120	Time: 11.90s
> [META]	Step: 121	Time: 12.00s
> [META]	Step: 122	Time: 12.10s
> [META]	Step: 123	Time: 12.20s
> [META]	Step: 124	Time: 12.30s
> [META]	Step: 125	Time: 12.40s
> [META]	Step: 126	Time: 12.50s
> [META]	Step: 127	Time: 12.60s
> [META]	Step: 128	Time: 12.70s
> [META]	Step: 129	Time: 12.80s
> [META]	Step: 130	Time: 12.90s
> [META]	Step: 131	Time: 13.00s
> [META]	Step: 132	Time: 13.10s
> [META]	Step: 133	Time: 13.20s
> [META]	Step: 134	Time: 13.30s
> [META]	Step: 135	Time: 13.40s
> [META]	Step: 136	Time: 13.50s
> [META]	Step: 137	Time: 13.60s
> [META]	Step: 138	Time: 13.70s
> [META]	Step: 139	Time: 13.80s
> [META]	Step: 140	Time: 13.90s
> [META]	Step: 141	Time: 14.00s
> [META]	Step: 142	Time: 14.10s
> [META]	Step: 143	Time: 14.20s
> [META]	Step: 144	Time: 14.30s
> [META]	Step: 145	Time: 14.40s
> [META]	Step: 146	Time: 14.50s
> [META]	Step: 147	Time: 14.60s
> [META]	Step: 148	Time: 14.70s
> [META]	Step: 149	Time: 14.80s
> [META]	Step: 150	Time: 14.90s
> [META]	Step: 151	Time: 15.00s
> [META]
> [META]	...SIMULATION COMPLETE
> [META]
> [OUTPUT]	Dumping initial simulation variables to output directory
> [OUTPUT]
> [OUTPUT]	Closing simulation.
> [OUTPUT]	Operation lasted 7.48s.
> [OUTPUT]	Moving to post-simulation analysis...
> [OUTPUT]
> [OUTPUT]	OMAS ANALYSIS TOOL...
> [OUTPUT]
> [OUTPUT]	Moving to event data parser...
> [OUTPUT]	Parsing simulation EVENT data...
> [OUTPUT]
> [OUTPUT]	EVENT statistics collected.
> [OUTPUT]
> [OUTPUT]	Moving to agent data parser...
> [OUTPUT]	Parsing AGENT data...
> 
> [OUTPUT]	OMAS FIGURE GENERATOR (OMAS_figureGenerator.m).
> [OUTPUT]
> [OUTPUT]	Generating the event overview figure.
> [OUTPUT}	Generating top-down 2D(plan) figure.
> Warning: [OMAS-error] A problem occurred generating the output figures. 
> > In OMAS_analysis (line 99)
> In OMAS_initialise (line 137)
> In example_setup (line 157) 
> Warning: Undefined function 'OMAS_getTrajectoryData_mex' for input arguments of type 'uint16'. 
> > In OMAS_analysis (line 100)
> In OMAS_initialise (line 137)
> In example_setup (line 157) 
> 
> Warning: [ERROR] A problem occurred interpreting the output data 
> > In OMAS_initialise (line 139)
> In example_setup (line 157) 
> Unrecognized function or variable 'OMAS_getTrajectoryData_mex'.
> 
> Error in GetFigure_plan (line 21)
>     [finalStates] = OMAS_getTrajectoryData_mex(...
> 
> Error in OMAS_figureGenerator (line 79)
>         [figureNumber,~] = GetFigure_plan(SIM,objectIndex,DATA,figureNumber);
> 
> Error in OMAS_analysis (line 97)
>         [plotnum] = OMAS_figureGenerator(META,OBJECTS,DATA,plotnum,figureList(figNum)); % Jump to the figure index
> 
> Error in OMAS_initialise (line 137)
>     [DATA] = OMAS_analysis(META,objectIndex,EVENTS,DATA);                  % Jump to external analysis program
> 
> Error in example_setup (line 157)
> [DATA,META] = OMAS_initialise('objects',objectIndex,...
>  
> >> 
> ```
> 
> I use m1 macbook, maybe need a `mexmaci64` instead `.mexw64`

Interesting, so this is indeed an issue with the mex generated for windows. You can use the non mex variant (by removing the '_mex') however, I have done this by default in another push.
